# fly.toml file generated for fly-gitea on 2023-02-10T10:38:31-05:00

app = "fly-gitea"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  GITEA_CUSTOM = "/app/custom/"
  GITEA__database__DB_TYPE = "sqlite3"
  GITEA__database__PATH = "/data/gitea/gitea.db"
  GITEA__security__INSTALL_LOCK = "true"
  GITEA__server__DOMAIN = "fly-gitea.fly.dev"
  GITEA__server__ROOT_URL = "https://fly-gitea.fly.dev"
  GITEA__server__SSH_DOMAIN = "fly-gitea.fly.dev"
  GITEA__service__DISABLE_REGISTRATION = "false"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "fly_gitea_data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
